//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerHistogramCheckpoint) DeepCopyInto(out *ContainerHistogramCheckpoint) {
	*out = *in
	in.CPUHistogram.DeepCopyInto(&out.CPUHistogram)
	in.MemoryHistogram.DeepCopyInto(&out.MemoryHistogram)
	in.FirstSampleStart.DeepCopyInto(&out.FirstSampleStart)
	in.LastSampleStart.DeepCopyInto(&out.LastSampleStart)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerHistogramCheckpoint.
func (in *ContainerHistogramCheckpoint) DeepCopy() *ContainerHistogramCheckpoint {
	if in == nil {
		return nil
	}
	out := new(ContainerHistogramCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSlice) DeepCopyInto(out *VerticalPodAutoscalerSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSlice.
func (in *VerticalPodAutoscalerSlice) DeepCopy() *VerticalPodAutoscalerSlice {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalPodAutoscalerSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceCheckpoint) DeepCopyInto(out *VerticalPodAutoscalerSliceCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceCheckpoint.
func (in *VerticalPodAutoscalerSliceCheckpoint) DeepCopy() *VerticalPodAutoscalerSliceCheckpoint {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalPodAutoscalerSliceCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceCheckpointList) DeepCopyInto(out *VerticalPodAutoscalerSliceCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerticalPodAutoscalerSliceCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceCheckpointList.
func (in *VerticalPodAutoscalerSliceCheckpointList) DeepCopy() *VerticalPodAutoscalerSliceCheckpointList {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalPodAutoscalerSliceCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceCheckpointSpec) DeepCopyInto(out *VerticalPodAutoscalerSliceCheckpointSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceCheckpointSpec.
func (in *VerticalPodAutoscalerSliceCheckpointSpec) DeepCopy() *VerticalPodAutoscalerSliceCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceCheckpointStatus) DeepCopyInto(out *VerticalPodAutoscalerSliceCheckpointStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	if in.ContainerCheckpoints != nil {
		in, out := &in.ContainerCheckpoints, &out.ContainerCheckpoints
		*out = make([]ContainerHistogramCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceCheckpointStatus.
func (in *VerticalPodAutoscalerSliceCheckpointStatus) DeepCopy() *VerticalPodAutoscalerSliceCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceList) DeepCopyInto(out *VerticalPodAutoscalerSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerticalPodAutoscalerSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceList.
func (in *VerticalPodAutoscalerSliceList) DeepCopy() *VerticalPodAutoscalerSliceList {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerticalPodAutoscalerSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceSpec) DeepCopyInto(out *VerticalPodAutoscalerSliceSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceSpec.
func (in *VerticalPodAutoscalerSliceSpec) DeepCopy() *VerticalPodAutoscalerSliceSpec {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscalerSliceStatus) DeepCopyInto(out *VerticalPodAutoscalerSliceStatus) {
	*out = *in
	if in.Recommendation != nil {
		in, out := &in.Recommendation, &out.Recommendation
		*out = new(v1.RecommendedPodResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.VerticalPodAutoscalerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscalerSliceStatus.
func (in *VerticalPodAutoscalerSliceStatus) DeepCopy() *VerticalPodAutoscalerSliceStatus {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscalerSliceStatus)
	in.DeepCopyInto(out)
	return out
}
