/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	apisautoscalingk8siov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1alpha1"
	versioned "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/informers/externalversions/internalinterfaces"
	autoscalingk8siov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/listers/autoscaling.k8s.io/v1alpha1"
	cache "k8s.io/client-go/tools/cache"
)

// VerticalPodAutoscalerSliceInformer provides access to a shared informer and lister for
// VerticalPodAutoscalerSlices. Prefer using the type-safe variant (see [TypedVerticalPodAutoscalerSliceInformer]).
type VerticalPodAutoscalerSliceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceLister
}

// TypedVerticalPodAutoscalerSliceInformer provides access to a shared informer and lister for
// VerticalPodAutoscalerSlices, including the type-safe TypedInformer variant.
// It is a superset of VerticalPodAutoscalerSliceInformer.
type TypedVerticalPodAutoscalerSliceInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VerticalPodAutoscalerSliceIndexInformer
	Lister() autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceLister
}

// VerticalPodAutoscalerSliceIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VerticalPodAutoscalerSliceIndexInformer cache.TypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice]

// VerticalPodAutoscalerSliceHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VerticalPodAutoscalerSlice.
type VerticalPodAutoscalerSliceHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice]

// VerticalPodAutoscalerSliceDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VerticalPodAutoscalerSlice.
type VerticalPodAutoscalerSliceDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice]

// VerticalPodAutoscalerSliceFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VerticalPodAutoscalerSlice.
type VerticalPodAutoscalerSliceFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice]

// VerticalPodAutoscalerSliceIndexers is a specialization of [cache.TypedIndexers] for VerticalPodAutoscalerSlice.
type VerticalPodAutoscalerSliceIndexers = cache.TypedIndexers[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice]

// DeletedVerticalPodAutoscalerSlice is a specialization of [cache.DeletedObject] for VerticalPodAutoscalerSlice.
type DeletedVerticalPodAutoscalerSlice = cache.DeletedObject[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice]

type verticalPodAutoscalerSliceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVerticalPodAutoscalerSliceInformer constructs a new informer for VerticalPodAutoscalerSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVerticalPodAutoscalerSliceInformer]).
func NewVerticalPodAutoscalerSliceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVerticalPodAutoscalerSliceInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVerticalPodAutoscalerSliceInformer constructs a new informer for VerticalPodAutoscalerSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVerticalPodAutoscalerSliceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VerticalPodAutoscalerSliceIndexers) VerticalPodAutoscalerSliceIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVerticalPodAutoscalerSliceInformer constructs a new informer for VerticalPodAutoscalerSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVerticalPodAutoscalerSliceInformer]).
func NewFilteredVerticalPodAutoscalerSliceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVerticalPodAutoscalerSliceInformer constructs a new informer for VerticalPodAutoscalerSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVerticalPodAutoscalerSliceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VerticalPodAutoscalerSliceIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VerticalPodAutoscalerSliceIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVerticalPodAutoscalerSliceInformerWithOptions constructs a new informer for VerticalPodAutoscalerSlice type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVerticalPodAutoscalerSliceInformerWithOptions]).
func NewVerticalPodAutoscalerSliceInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceInformerWithOptions(client, namespace, options)
}

// NewTypedVerticalPodAutoscalerSliceInformerWithOptions constructs a new informer for VerticalPodAutoscalerSlice type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVerticalPodAutoscalerSliceInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VerticalPodAutoscalerSliceIndexInformer {
	gvr := schema.GroupVersionResource{Group: "autoscaling.k8s.io", Version: "v1alpha1", Resource: "verticalpodautoscalerslices"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSlices(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSlices(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSlices(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSlices(namespace).Watch(ctx, opts)
			},
		}, client),
		&apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *verticalPodAutoscalerSliceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *verticalPodAutoscalerSliceInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *verticalPodAutoscalerSliceInformer) TypedInformer() VerticalPodAutoscalerSliceIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice](f.factory.InformerFor(&apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice{}, f.defaultInformer))
}

func (f *verticalPodAutoscalerSliceInformer) Lister() autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceLister {
	return autoscalingk8siov1alpha1.NewVerticalPodAutoscalerSliceLister(f.Informer().GetIndexer())
}

// ToTypedVerticalPodAutoscalerSliceInformer converts an untyped informer into a TypedVerticalPodAutoscalerSliceInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VerticalPodAutoscalerSlice. If that is not the case, calling type-safe methods of the returned
// TypedVerticalPodAutoscalerSliceInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVerticalPodAutoscalerSliceInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVerticalPodAutoscalerSliceInformer(informer VerticalPodAutoscalerSliceInformer) TypedVerticalPodAutoscalerSliceInformer {
	if informer, ok := informer.(TypedVerticalPodAutoscalerSliceInformer); ok {
		return informer
	}
	return &verticalPodAutoscalerSliceTypedInformerAdapter{informer}
}

type verticalPodAutoscalerSliceTypedInformerAdapter struct {
	VerticalPodAutoscalerSliceInformer
}

func (a *verticalPodAutoscalerSliceTypedInformerAdapter) TypedInformer() VerticalPodAutoscalerSliceIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice](a.Informer())
}

// ToVerticalPodAutoscalerSliceIndexInformer converts an untyped informer into a VerticalPodAutoscalerSliceIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VerticalPodAutoscalerSlice. If that is not the case, calling type-safe methods of the returned
// VerticalPodAutoscalerSliceIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VerticalPodAutoscalerSliceIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVerticalPodAutoscalerSliceIndexInformer(informer cache.SharedIndexInformer) VerticalPodAutoscalerSliceIndexInformer {
	if informer, ok := informer.(VerticalPodAutoscalerSliceIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSlice](informer)
}
