/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	apisautoscalingk8siov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1alpha1"
	versioned "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/informers/externalversions/internalinterfaces"
	autoscalingk8siov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/listers/autoscaling.k8s.io/v1alpha1"
	cache "k8s.io/client-go/tools/cache"
)

// VerticalPodAutoscalerSliceCheckpointInformer provides access to a shared informer and lister for
// VerticalPodAutoscalerSliceCheckpoints. Prefer using the type-safe variant (see [TypedVerticalPodAutoscalerSliceCheckpointInformer]).
type VerticalPodAutoscalerSliceCheckpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointLister
}

// TypedVerticalPodAutoscalerSliceCheckpointInformer provides access to a shared informer and lister for
// VerticalPodAutoscalerSliceCheckpoints, including the type-safe TypedInformer variant.
// It is a superset of VerticalPodAutoscalerSliceCheckpointInformer.
type TypedVerticalPodAutoscalerSliceCheckpointInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() VerticalPodAutoscalerSliceCheckpointIndexInformer
	Lister() autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointLister
}

// VerticalPodAutoscalerSliceCheckpointIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type VerticalPodAutoscalerSliceCheckpointIndexInformer cache.TypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint]

// VerticalPodAutoscalerSliceCheckpointHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for VerticalPodAutoscalerSliceCheckpoint.
type VerticalPodAutoscalerSliceCheckpointHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint]

// VerticalPodAutoscalerSliceCheckpointDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for VerticalPodAutoscalerSliceCheckpoint.
type VerticalPodAutoscalerSliceCheckpointDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint]

// VerticalPodAutoscalerSliceCheckpointFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for VerticalPodAutoscalerSliceCheckpoint.
type VerticalPodAutoscalerSliceCheckpointFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint]

// VerticalPodAutoscalerSliceCheckpointIndexers is a specialization of [cache.TypedIndexers] for VerticalPodAutoscalerSliceCheckpoint.
type VerticalPodAutoscalerSliceCheckpointIndexers = cache.TypedIndexers[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint]

// DeletedVerticalPodAutoscalerSliceCheckpoint is a specialization of [cache.DeletedObject] for VerticalPodAutoscalerSliceCheckpoint.
type DeletedVerticalPodAutoscalerSliceCheckpoint = cache.DeletedObject[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint]

type verticalPodAutoscalerSliceCheckpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVerticalPodAutoscalerSliceCheckpointInformer constructs a new informer for VerticalPodAutoscalerSliceCheckpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVerticalPodAutoscalerSliceCheckpointInformer]).
func NewVerticalPodAutoscalerSliceCheckpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedVerticalPodAutoscalerSliceCheckpointInformer constructs a new informer for VerticalPodAutoscalerSliceCheckpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVerticalPodAutoscalerSliceCheckpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VerticalPodAutoscalerSliceCheckpointIndexers) VerticalPodAutoscalerSliceCheckpointIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredVerticalPodAutoscalerSliceCheckpointInformer constructs a new informer for VerticalPodAutoscalerSliceCheckpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredVerticalPodAutoscalerSliceCheckpointInformer]).
func NewFilteredVerticalPodAutoscalerSliceCheckpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredVerticalPodAutoscalerSliceCheckpointInformer constructs a new informer for VerticalPodAutoscalerSliceCheckpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredVerticalPodAutoscalerSliceCheckpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers VerticalPodAutoscalerSliceCheckpointIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) VerticalPodAutoscalerSliceCheckpointIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewVerticalPodAutoscalerSliceCheckpointInformerWithOptions constructs a new informer for VerticalPodAutoscalerSliceCheckpoint type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions]).
func NewVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client, namespace, options)
}

// NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions constructs a new informer for VerticalPodAutoscalerSliceCheckpoint type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) VerticalPodAutoscalerSliceCheckpointIndexInformer {
	gvr := schema.GroupVersionResource{Group: "autoscaling.k8s.io", Version: "v1alpha1", Resource: "verticalpodautoscalerslicecheckpoints"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSliceCheckpoints(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSliceCheckpoints(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSliceCheckpoints(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.AutoscalingV1alpha1().VerticalPodAutoscalerSliceCheckpoints(namespace).Watch(ctx, opts)
			},
		}, client),
		&apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *verticalPodAutoscalerSliceCheckpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedVerticalPodAutoscalerSliceCheckpointInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *verticalPodAutoscalerSliceCheckpointInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *verticalPodAutoscalerSliceCheckpointInformer) TypedInformer() VerticalPodAutoscalerSliceCheckpointIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint](f.factory.InformerFor(&apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint{}, f.defaultInformer))
}

func (f *verticalPodAutoscalerSliceCheckpointInformer) Lister() autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointLister {
	return autoscalingk8siov1alpha1.NewVerticalPodAutoscalerSliceCheckpointLister(f.Informer().GetIndexer())
}

// ToTypedVerticalPodAutoscalerSliceCheckpointInformer converts an untyped informer into a TypedVerticalPodAutoscalerSliceCheckpointInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VerticalPodAutoscalerSliceCheckpoint. If that is not the case, calling type-safe methods of the returned
// TypedVerticalPodAutoscalerSliceCheckpointInformer leads to runtime panics. A safer alternative is to pass
// around a TypedVerticalPodAutoscalerSliceCheckpointInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedVerticalPodAutoscalerSliceCheckpointInformer(informer VerticalPodAutoscalerSliceCheckpointInformer) TypedVerticalPodAutoscalerSliceCheckpointInformer {
	if informer, ok := informer.(TypedVerticalPodAutoscalerSliceCheckpointInformer); ok {
		return informer
	}
	return &verticalPodAutoscalerSliceCheckpointTypedInformerAdapter{informer}
}

type verticalPodAutoscalerSliceCheckpointTypedInformerAdapter struct {
	VerticalPodAutoscalerSliceCheckpointInformer
}

func (a *verticalPodAutoscalerSliceCheckpointTypedInformerAdapter) TypedInformer() VerticalPodAutoscalerSliceCheckpointIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint](a.Informer())
}

// ToVerticalPodAutoscalerSliceCheckpointIndexInformer converts an untyped informer into a VerticalPodAutoscalerSliceCheckpointIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *VerticalPodAutoscalerSliceCheckpoint. If that is not the case, calling type-safe methods of the returned
// VerticalPodAutoscalerSliceCheckpointIndexInformer leads to runtime panics. A safer alternative is to pass
// around a VerticalPodAutoscalerSliceCheckpointIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToVerticalPodAutoscalerSliceCheckpointIndexInformer(informer cache.SharedIndexInformer) VerticalPodAutoscalerSliceCheckpointIndexInformer {
	if informer, ok := informer.(VerticalPodAutoscalerSliceCheckpointIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisautoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint](informer)
}
