/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	autoscalingk8siov1alpha1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1alpha1"
	scheme "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/scheme"
	gentype "k8s.io/client-go/gentype"
)

// VerticalPodAutoscalerSliceCheckpointsGetter has a method to return a VerticalPodAutoscalerSliceCheckpointInterface.
// A group's client should implement this interface.
type VerticalPodAutoscalerSliceCheckpointsGetter interface {
	VerticalPodAutoscalerSliceCheckpoints(namespace string) VerticalPodAutoscalerSliceCheckpointInterface
}

// VerticalPodAutoscalerSliceCheckpointInterface has methods to work with VerticalPodAutoscalerSliceCheckpoint resources.
type VerticalPodAutoscalerSliceCheckpointInterface interface {
	Create(ctx context.Context, verticalPodAutoscalerSliceCheckpoint *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, opts v1.CreateOptions) (*autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, error)
	Update(ctx context.Context, verticalPodAutoscalerSliceCheckpoint *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, opts v1.UpdateOptions) (*autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, err error)
	VerticalPodAutoscalerSliceCheckpointExpansion
}

// verticalPodAutoscalerSliceCheckpoints implements VerticalPodAutoscalerSliceCheckpointInterface
type verticalPodAutoscalerSliceCheckpoints struct {
	*gentype.ClientWithList[*autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointList]
}

// newVerticalPodAutoscalerSliceCheckpoints returns a VerticalPodAutoscalerSliceCheckpoints
func newVerticalPodAutoscalerSliceCheckpoints(c *AutoscalingV1alpha1Client, namespace string) *verticalPodAutoscalerSliceCheckpoints {
	return &verticalPodAutoscalerSliceCheckpoints{
		gentype.NewClientWithList[*autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint, *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointList](
			"verticalpodautoscalerslicecheckpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint {
				return &autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpoint{}
			},
			func() *autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointList {
				return &autoscalingk8siov1alpha1.VerticalPodAutoscalerSliceCheckpointList{}
			},
		),
	}
}
