/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	autoscalingk8siov1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VerticalPodAutoscalerSliceCheckpointLister helps list VerticalPodAutoscalerSliceCheckpoints.
// All objects returned here must be treated as read-only.
type VerticalPodAutoscalerSliceCheckpointLister interface {
	// List lists all VerticalPodAutoscalerSliceCheckpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint, err error)
	// VerticalPodAutoscalerSliceCheckpoints returns an object that can list and get VerticalPodAutoscalerSliceCheckpoints.
	VerticalPodAutoscalerSliceCheckpoints(namespace string) VerticalPodAutoscalerSliceCheckpointNamespaceLister
	VerticalPodAutoscalerSliceCheckpointListerExpansion
}

// verticalPodAutoscalerSliceCheckpointLister implements the VerticalPodAutoscalerSliceCheckpointLister interface.
type verticalPodAutoscalerSliceCheckpointLister struct {
	listers.ResourceIndexer[*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint]
}

// NewVerticalPodAutoscalerSliceCheckpointLister returns a new VerticalPodAutoscalerSliceCheckpointLister.
func NewVerticalPodAutoscalerSliceCheckpointLister(indexer cache.Indexer) VerticalPodAutoscalerSliceCheckpointLister {
	return &verticalPodAutoscalerSliceCheckpointLister{listers.New[*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint](indexer, autoscalingk8siov1.Resource("verticalpodautoscalerslicecheckpoint"))}
}

// VerticalPodAutoscalerSliceCheckpoints returns an object that can list and get VerticalPodAutoscalerSliceCheckpoints.
func (s *verticalPodAutoscalerSliceCheckpointLister) VerticalPodAutoscalerSliceCheckpoints(namespace string) VerticalPodAutoscalerSliceCheckpointNamespaceLister {
	return verticalPodAutoscalerSliceCheckpointNamespaceLister{listers.NewNamespaced[*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint](s.ResourceIndexer, namespace)}
}

// VerticalPodAutoscalerSliceCheckpointNamespaceLister helps list and get VerticalPodAutoscalerSliceCheckpoints.
// All objects returned here must be treated as read-only.
type VerticalPodAutoscalerSliceCheckpointNamespaceLister interface {
	// List lists all VerticalPodAutoscalerSliceCheckpoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint, err error)
	// Get retrieves the VerticalPodAutoscalerSliceCheckpoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint, error)
	VerticalPodAutoscalerSliceCheckpointNamespaceListerExpansion
}

// verticalPodAutoscalerSliceCheckpointNamespaceLister implements the VerticalPodAutoscalerSliceCheckpointNamespaceLister
// interface.
type verticalPodAutoscalerSliceCheckpointNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingk8siov1.VerticalPodAutoscalerSliceCheckpoint]
}
