/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	autoscalingk8siov1 "k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VerticalPodAutoscalerSliceLister helps list VerticalPodAutoscalerSlices.
// All objects returned here must be treated as read-only.
type VerticalPodAutoscalerSliceLister interface {
	// List lists all VerticalPodAutoscalerSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingk8siov1.VerticalPodAutoscalerSlice, err error)
	// VerticalPodAutoscalerSlices returns an object that can list and get VerticalPodAutoscalerSlices.
	VerticalPodAutoscalerSlices(namespace string) VerticalPodAutoscalerSliceNamespaceLister
	VerticalPodAutoscalerSliceListerExpansion
}

// verticalPodAutoscalerSliceLister implements the VerticalPodAutoscalerSliceLister interface.
type verticalPodAutoscalerSliceLister struct {
	listers.ResourceIndexer[*autoscalingk8siov1.VerticalPodAutoscalerSlice]
}

// NewVerticalPodAutoscalerSliceLister returns a new VerticalPodAutoscalerSliceLister.
func NewVerticalPodAutoscalerSliceLister(indexer cache.Indexer) VerticalPodAutoscalerSliceLister {
	return &verticalPodAutoscalerSliceLister{listers.New[*autoscalingk8siov1.VerticalPodAutoscalerSlice](indexer, autoscalingk8siov1.Resource("verticalpodautoscalerslice"))}
}

// VerticalPodAutoscalerSlices returns an object that can list and get VerticalPodAutoscalerSlices.
func (s *verticalPodAutoscalerSliceLister) VerticalPodAutoscalerSlices(namespace string) VerticalPodAutoscalerSliceNamespaceLister {
	return verticalPodAutoscalerSliceNamespaceLister{listers.NewNamespaced[*autoscalingk8siov1.VerticalPodAutoscalerSlice](s.ResourceIndexer, namespace)}
}

// VerticalPodAutoscalerSliceNamespaceLister helps list and get VerticalPodAutoscalerSlices.
// All objects returned here must be treated as read-only.
type VerticalPodAutoscalerSliceNamespaceLister interface {
	// List lists all VerticalPodAutoscalerSlices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingk8siov1.VerticalPodAutoscalerSlice, err error)
	// Get retrieves the VerticalPodAutoscalerSlice from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingk8siov1.VerticalPodAutoscalerSlice, error)
	VerticalPodAutoscalerSliceNamespaceListerExpansion
}

// verticalPodAutoscalerSliceNamespaceLister implements the VerticalPodAutoscalerSliceNamespaceLister
// interface.
type verticalPodAutoscalerSliceNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingk8siov1.VerticalPodAutoscalerSlice]
}
